### ISSUE TITLE
WithPosition accepts request, but employee doesnt appear in Employees app

### ISSUE THREAD

**Issue by taviandir** [visma-net/employee-public-api-docs#1]
**Describe the bug**
I've sent countless variations of the request to POST /v1/employees/withPosition, the endpoint seemingly accepting the request. But when I look in our Visma.Net Employees app, the user doesnt appear in the list. As far as I can tell, I have all the required information provided in accordance with the example at https://github.com/visma-net/employee-public-api-docs/blob/main/FAQ.md#minimal-set-of-mandatory-fields-for-post-employeeswithposition

**To Reproduce**
1. POST /v1/employees/withPosition (with request json below)
2. Get 202 Accepted response
3. Go to Visma.Net Employee app
4. Employee is not in the list of active employees

**Expected behavior**
If there is any information lacking in the request, I would expect to get a validation error describing what is wrong or missing with the request body.
If all required fields are set and valid, I would expect the employee to appear in the "Active Employees" list in the Employees app.

**Screenshots**
![image](https://user-images.githubusercontent.com/10051884/145788103-b17c135c-4920-4650-9d51-a022fdea9a82.png)
![image](https://user-images.githubusercontent.com/10051884/145788310-71b3b6ad-1636-440f-939d-6480401b1324.png)

**Additional context**
This is the request body that I've been using. Things of note:
1) The person is fictive, and the email, phone number and national ID number are also fictive (but valid).
2) I am testing on our demo tenant, if that makes any difference.

```
{
  "printPayslip": false,
  "number": "13371337",
  "dateOfBirth": "1965-12-08",
  "emails": [
    {
      "type": "private",
      "address": "marius.andersen420@gmail.com"
    }
  ],
  "phones": [
    {
      "type": "private",
      "number": "99119900"
    }
  ],
  "personIds": [
    {
      "typeOfId": "NationalID",
      "typeOfInternationalId": null,
      "id": "08126597119",
      "activeStart": null,
      "activeEnd": null
    }
  ],
  "personNames": [
    {
      "firstName": "Marius",
      "lastName": "Andersen",
      "activeStart": null,
      "activeEnd": null
    }
  ],
  "address": {
    "countryCode": "NO"
  },
  "salaryPaymentMethod": {
    "paymentType": "cash"
  },
  "taxInformation": {
    "mainEmployer": true
  },
  "positions": [
    {
      "activeStart": "2019-06-03",
      "typeOfPosition": "Ordinary",
      "employmentForm": [
        {
          "value": "fast"
        }
      ],
      "typeOfWork": [
        {
          "value": "4121101"
        }
      ],
      "workTimeAgreement": [
        {
          "value": "0387f476-2471-4816-8b94-cdabb8fe4c21"
        }
      ],
      "partTimeFactors": [
        {
          "value": 100
        }
      ],
      "salaryInformation": [
        {
          "salaryType": "Period",
          "monthlySalary": "41667"
        }
      ]
    }
  ]
}
```

Please let me know if there is any more information you need from me.

**Comment by taviandir** [comment]
I just tried the example payload in the FAQ.md, and that one works. What am I doing wrong with my request payload?
The first thing I notice is that the "workTimeAgreement" value is very different than the one I am posting. The example's format is a format that does not comply with what the documentation is saying. What is that format in the example based on?

![image](https://user-images.githubusercontent.com/10051884/145791724-7bb43e9b-d136-4db8-8e1f-4fa1476244c4.png)

Documentation:
![image](https://user-images.githubusercontent.com/10051884/145791228-47443cf0-81d8-49c9-b534-ccb88a859df9.png)

FAQ example:
![image](https://user-images.githubusercontent.com/10051884/145791303-b6d07c34-a03a-4776-a168-01b7655176a5.png)

**Comment by martins-abolins** [comment]
Thank you @taviandir for reporting this issue. FAQ.md has now been updated. Sample payload now uses one of the values provided in Swagger documentation. 

![image](https://user-images.githubusercontent.com/71688882/145809647-fba94506-4234-42d8-a537-4c3c21ebce74.png)


> I just tried the example payload in the FAQ.md, and that one works. What am I doing wrong with my request payload? The first thing I notice is that the "workTimeAgreement" value is very different than the one I am posting. The example's format is a format that does not comply with what the documentation is saying. What is that format in the example based on?
> 
> ![image](https://user-images.githubusercontent.com/10051884/145791724-7bb43e9b-d136-4db8-8e1f-4fa1476244c4.png)
> 
> Documentation: ![image](https://user-images.githubusercontent.com/10051884/145791228-47443cf0-81d8-49c9-b534-ccb88a859df9.png)
> 
> FAQ example: ![image](https://user-images.githubusercontent.com/10051884/145791303-b6d07c34-a03a-4776-a168-01b7655176a5.png)

**Comment by martins-abolins** [comment]
Hi @taviandir 
When a POST request is accepted, a job is created for background processing. In response header you will find "Location" attribute. Query the location to get job details: execution status, message in case of an error and other information. 

Also, in the payload that you use, type of phone is case sensitive. Swagger documentation will be updated to include this information. Use the following values instead
```
"phones": [
    {
      "type": "Private",
      "number": "99119900"
    }
  ],
```

![image](https://user-images.githubusercontent.com/71688882/145812309-7c21da17-f4d0-4cba-b167-cc9b959ae7f1.png)



> **Describe the bug** I've sent countless variations of the request to POST /v1/employees/withPosition, the endpoint seemingly accepting the request. But when I look in our Visma.Net Employees app, the user doesnt appear in the list. As far as I can tell, I have all the required information provided in accordance with the example at https://github.com/visma-net/employee-public-api-docs/blob/main/FAQ.md#minimal-set-of-mandatory-fields-for-post-employeeswithposition
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. POST /v1/employees/withPosition (with request json below)
> 2. Get 202 Accepted response
> 3. Go to Visma.Net Employee app
> 4. Employee is not in the list of active employees
> 
> **Expected behavior** If there is any information lacking in the request, I would expect to get a validation error describing what is wrong or missing with the request body. If all required fields are set and valid, I would expect the employee to appear in the "Active Employees" list in the Employees app.
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/10051884/145788103-b17c135c-4920-4650-9d51-a022fdea9a82.png) ![image](https://user-images.githubusercontent.com/10051884/145788310-71b3b6ad-1636-440f-939d-6480401b1324.png)
> 
> **Additional context** This is the request body that I've been using. Things of note:
> 
> 1. The person is fictive, and the email, phone number and national ID number are also fictive (but valid).
> 2. I am testing on our demo tenant, if that makes any difference.
> 
> ```
> {
>   "printPayslip": false,
>   "number": "13371337",
>   "dateOfBirth": "1965-12-08",
>   "emails": [
>     {
>       "type": "private",
>       "address": "marius.andersen420@gmail.com"
>     }
>   ],
>   "phones": [
>     {
>       "type": "private",
>       "number": "99119900"
>     }
>   ],
>   "personIds": [
>     {
>       "typeOfId": "NationalID",
>       "typeOfInternationalId": null,
>       "id": "08126597119",
>       "activeStart": null,
>       "activeEnd": null
>     }
>   ],
>   "personNames": [
>     {
>       "firstName": "Marius",
>       "lastName": "Andersen",
>       "activeStart": null,
>       "activeEnd": null
>     }
>   ],
>   "address": {
>     "countryCode": "NO"
>   },
>   "salaryPaymentMethod": {
>     "paymentType": "cash"
>   },
>   "taxInformation": {
>     "mainEmployer": true
>   },
>   "positions": [
>     {
>       "activeStart": "2019-06-03",
>       "typeOfPosition": "Ordinary",
>       "employmentForm": [
>         {
>           "value": "fast"
>         }
>       ],
>       "typeOfWork": [
>         {
>           "value": "4121101"
>         }
>       ],
>       "workTimeAgreement": [
>         {
>           "value": "0387f476-2471-4816-8b94-cdabb8fe4c21"
>         }
>       ],
>       "partTimeFactors": [
>         {
>           "value": 100
>         }
>       ],
>       "salaryInformation": [
>         {
>           "salaryType": "Period",
>           "monthlySalary": "41667"
>         }
>       ]
>     }
>   ]
> }
> ```
> 
> Please let me know if there is any more information you need from me.

**Comment by taviandir** [comment]
Thanks for your quick reply!

I tried checking the job's details, and it provided me with the following validation errors:

```json
{
            "id": "4169ed2f-b49f-4fae-af1e-a85feebbfe4e",
            "message": "The reference list of field Phone type does not contain the value supplied (private).",
            "value": "Private",
            "severity": "Error"
        },
        {
            "id": "4169ed2f-b49f-4fae-af1e-a85feebbfe4e",
            "message": "The reference list of field E-mail type does not contain the value supplied (private).",
            "value": "Private",
            "severity": "Error"
        },
        {
            "id": "f8c50dc3-4c81-4ffd-bae2-68558440877f",
            "message": "Tax unit employee is missing a value.",
            "severity": "Error"
        },
        {
            "id": "4169ed2f-b49f-4fae-af1e-a85feebbfe4e",
            "message": "The reference list of field Phone type does not contain the value supplied (private).",
            "value": "Private",
            "severity": "Warning"
        },
        {
            "id": "4169ed2f-b49f-4fae-af1e-a85feebbfe4e",
            "message": "The reference list of field E-mail type does not contain the value supplied (private).",
            "value": "Private",
            "severity": "Warning"
        }
```

Can you help me understand these better? I see 3 issues with these validation messages:

(1): "Tax unit employee is missing a value."
The documentation says that I shouldnt need to provide a value for this, since it claims "that it will be prefilled automatically". As such, I also have no value to provide for this property from the documentation.
![image](https://user-images.githubusercontent.com/10051884/145817787-d6cc9096-f36a-4af2-92b7-60a9fb22f3e4.png)


(2): Email and phone errors: "The reference list of field E-mail type does not contain the value supplied (private)"

Here we can see that I've set "type": "private" ...
![image](https://user-images.githubusercontent.com/10051884/145817841-dfd1cb30-613c-4c94-a4e5-4d9886288614.png)

... which the documentation states that this is a valid value. So why am I getting an error for this? What is the correct value to put for a private email and phone?
![image](https://user-images.githubusercontent.com/10051884/145817999-342384ed-5ec4-4d1b-8893-05ecfa7ff979.png)


(3): For the phone and email validations, I'm getting both an Error and a Warning for the same validation error. It's either an error or a warning - not both, wouldn't you agree? :)

**Comment by martins-abolins** [comment]
- Phone number type: there was an error in the documentation. Type of phone is case sensitive and correct value for type is "Private" or "Business", starting with capital letter. Swagger documentation will be updated during the day to include this information and correct example values. To overcome reported errors, use following values instead:
```
"phones": [
    {
      "type": "Private",
      "number": "99119900"
    }
  ]
```
- Tax Units. Unfortunately a the moment you cannot query for available values yourself. Tax Unit details will be a feature of a new Organizations API that will be release in beginning of 2022. 
By design, in case  you only have one Tax Unit, it will be selected automatically for the Employee you are creating. We are checking why it was not automatically picked up for you. 
Meanwhile, please try adding the following to your payload for the Position: 
```
"taxUnitIds": [
    {
       "value": "2"
    }
 ]
```

**Comment by taviandir** [comment]
Great, thanks! With these changes, I could successfully post a new employee. 😀

![image](https://user-images.githubusercontent.com/10051884/145973513-d1c043b8-609f-42f8-97b6-9cd95ac04f71.png)

Excited to hear about the Organizations API. Will the release of this API lead to a breaking change in regards to providing a value for `Position.taxUnitIds`?

**Comment by martins-abolins** [comment]
Great to see that it works!
Backwards compatibility will be supported for entities like Position TaxUnits and others where applicable.
