### ISSUE TITLE
Enhancement: add support for function/ job profile and org units

### ISSUE THREAD

**Issue by sveldhuisen** [visma-net/employee-public-api-docs#2]
Hi,

As an independend software vendor we are integrating Visma.net HRM with our Identity & Access management solution for the Dutch educational market. Compared to Youforce and other HR vendors (i.e. AFAS) we are missing some data to make our integration useful. I.e.:

* the employee positions don't have a pointer id available to the related organization unit
* the employee positions don't have a pointer id available to the related function (a.k.a. Job Profiles)

We already have an integration with the Visma IAM API for Youforce which has this information available:

* Functions/ Job profiles (https://community.visma.com/t5/Kennisbank-Youforce-API/IAM-Domain-model-amp-field-mapping/ta-p/428102#toc-hId-209349616)
* Organization Units (https://community.visma.com/t5/Kennisbank-Youforce-API/IAM-Domain-model-amp-field-mapping/ta-p/428102#toc-hId-1018696242)
* Position referring to Functions/ Job profiles and Organization Units (https://community.visma.com/t5/Kennisbank-Youforce-API/IAM-Domain-model-amp-field-mapping/ta-p/428102#toc-hId-85232533)

It would be quite useful if the Employee API would contain those extra endpoints and data for Visma.net. I.e. our IAM solution could do access management decisions based on the Function/ Job profile and/ or Organization Unit that the active position is connected with.

Let me know if you have any further questions,

Kind regards,

Sebastiaan

**Comment by martins-abolins** [comment]
Hello @sveldhuisen 
We are grateful for you feedback! 
Currently API has been designed and targeted for Norwegian market and does not support needs of Dutch organizations. 
There are no short term plans to support this at the moment. 

Good luck and maybe we meet again later down the road.
