### ISSUE TITLE
Is this API available for other countries aswell?

### ISSUE THREAD

**Issue by Jarola-DS** [visma-net/employee-public-api-docs#3]
Documentation states Norwegian only i believe. Is this Public API usable by, for example, a tenant in the Netherlands if we just use the Oath2.0 authentication? Or does the back-end differ from eachother?

**Comment by martins-abolins** [comment]
Thank you for reaching out to us regarding our API. We appreciate your interest in our services.
We would like to inform you that our API is specifically designed to work with Visma Payroll in Norway. Unfortunately, it is not supported for use in other countries at this time.
If you have any further questions or if there is anything else we can assist you with, please don't hesitate to let us know. We are here to help.
Thank you for your understanding.
