### ISSUE TITLE
Missing API to get leader

### ISSUE THREAD

**Issue by eweaner** [visma-net/employee-public-api-docs#4]
I want to get the leader field trough API

**Comment by martins-abolins** [comment]
Thank you for reaching out! 
Manager (Leder) field is in pipeline to be released with a few other fields in one of the next releases, during Q4 this year. 
To stay updated on our product releases and new features, keep subscribed and follow updates on this repo. 

If you have any further questions or need assistance, please don't hesitate to reach out
